/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugIndexRouteImport } from './routes/$storeSlug/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as DashboardSellerRouteImport } from './routes/dashboard/seller'
import { Route as DashboardDriverRouteImport } from './routes/dashboard/driver'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard/buyer'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as StoreSlugProductSlugRouteImport } from './routes/$storeSlug/$productSlug'
import { Route as DashboardSellerIndexRouteImport } from './routes/dashboard/seller/index'
import { Route as DashboardBuyerIndexRouteImport } from './routes/dashboard/buyer/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardSellerStoreRouteImport } from './routes/dashboard/seller/store'
import { Route as DashboardSellerReportRouteImport } from './routes/dashboard/seller/report'
import { Route as DashboardSellerOnboardingRouteImport } from './routes/dashboard/seller/onboarding'
import { Route as DashboardBuyerWalletRouteImport } from './routes/dashboard/buyer/wallet'
import { Route as DashboardBuyerReportRouteImport } from './routes/dashboard/buyer/report'
import { Route as DashboardBuyerCheckoutRouteImport } from './routes/dashboard/buyer/checkout'
import { Route as DashboardBuyerCartRouteImport } from './routes/dashboard/buyer/cart'
import { Route as DashboardBuyerAddressesRouteImport } from './routes/dashboard/buyer/addresses'
import { Route as DashboardAdminDiscountsRouteImport } from './routes/dashboard/admin/discounts'
import { Route as DashboardSellerProductsIndexRouteImport } from './routes/dashboard/seller/products/index'
import { Route as DashboardSellerOrdersIndexRouteImport } from './routes/dashboard/seller/orders/index'
import { Route as DashboardBuyerOrdersIndexRouteImport } from './routes/dashboard/buyer/orders/index'
import { Route as DashboardSellerProductsCreateRouteImport } from './routes/dashboard/seller/products/create'
import { Route as DashboardSellerOrdersOrderIdRouteImport } from './routes/dashboard/seller/orders/$orderId'
import { Route as DashboardBuyerOrdersOrderIdRouteImport } from './routes/dashboard/buyer/orders/$orderId'
import { Route as DashboardSellerProductsProductIdEditRouteImport } from './routes/dashboard/seller/products/$productId/edit'

const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugIndexRoute = StoreSlugIndexRouteImport.update({
  id: '/$storeSlug/',
  path: '/$storeSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/dashboard/seller',
  path: '/dashboard/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugProductSlugRoute = StoreSlugProductSlugRouteImport.update({
  id: '/$storeSlug/$productSlug',
  path: '/$storeSlug/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerIndexRoute = DashboardSellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSellerRoute,
} as any)
const DashboardBuyerIndexRoute = DashboardBuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardSellerStoreRoute = DashboardSellerStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DashboardSellerRoute,
} as any)
const DashboardSellerReportRoute = DashboardSellerReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DashboardSellerRoute,
} as any)
const DashboardSellerOnboardingRoute =
  DashboardSellerOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => DashboardSellerRoute,
  } as any)
const DashboardBuyerWalletRoute = DashboardBuyerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardBuyerReportRoute = DashboardBuyerReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardBuyerCheckoutRoute = DashboardBuyerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardBuyerCartRoute = DashboardBuyerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardBuyerAddressesRoute = DashboardBuyerAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardAdminDiscountsRoute = DashboardAdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardSellerProductsIndexRoute =
  DashboardSellerProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => DashboardSellerRoute,
  } as any)
const DashboardSellerOrdersIndexRoute =
  DashboardSellerOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => DashboardSellerRoute,
  } as any)
const DashboardBuyerOrdersIndexRoute =
  DashboardBuyerOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => DashboardBuyerRoute,
  } as any)
const DashboardSellerProductsCreateRoute =
  DashboardSellerProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => DashboardSellerRoute,
  } as any)
const DashboardSellerOrdersOrderIdRoute =
  DashboardSellerOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => DashboardSellerRoute,
  } as any)
const DashboardBuyerOrdersOrderIdRoute =
  DashboardBuyerOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => DashboardBuyerRoute,
  } as any)
const DashboardSellerProductsProductIdEditRoute =
  DashboardSellerProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => DashboardSellerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/$storeSlug/$productSlug': typeof StoreSlugProductSlugRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteWithChildren
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/seller': typeof DashboardSellerRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/$storeSlug/': typeof StoreSlugIndexRoute
  '/dashboard/admin/discounts': typeof DashboardAdminDiscountsRoute
  '/dashboard/buyer/addresses': typeof DashboardBuyerAddressesRoute
  '/dashboard/buyer/cart': typeof DashboardBuyerCartRoute
  '/dashboard/buyer/checkout': typeof DashboardBuyerCheckoutRoute
  '/dashboard/buyer/report': typeof DashboardBuyerReportRoute
  '/dashboard/buyer/wallet': typeof DashboardBuyerWalletRoute
  '/dashboard/seller/onboarding': typeof DashboardSellerOnboardingRoute
  '/dashboard/seller/report': typeof DashboardSellerReportRoute
  '/dashboard/seller/store': typeof DashboardSellerStoreRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
  '/dashboard/seller/': typeof DashboardSellerIndexRoute
  '/dashboard/buyer/orders/$orderId': typeof DashboardBuyerOrdersOrderIdRoute
  '/dashboard/seller/orders/$orderId': typeof DashboardSellerOrdersOrderIdRoute
  '/dashboard/seller/products/create': typeof DashboardSellerProductsCreateRoute
  '/dashboard/buyer/orders/': typeof DashboardBuyerOrdersIndexRoute
  '/dashboard/seller/orders/': typeof DashboardSellerOrdersIndexRoute
  '/dashboard/seller/products/': typeof DashboardSellerProductsIndexRoute
  '/dashboard/seller/products/$productId/edit': typeof DashboardSellerProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/$storeSlug/$productSlug': typeof StoreSlugProductSlugRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/$storeSlug': typeof StoreSlugIndexRoute
  '/dashboard/admin/discounts': typeof DashboardAdminDiscountsRoute
  '/dashboard/buyer/addresses': typeof DashboardBuyerAddressesRoute
  '/dashboard/buyer/cart': typeof DashboardBuyerCartRoute
  '/dashboard/buyer/checkout': typeof DashboardBuyerCheckoutRoute
  '/dashboard/buyer/report': typeof DashboardBuyerReportRoute
  '/dashboard/buyer/wallet': typeof DashboardBuyerWalletRoute
  '/dashboard/seller/onboarding': typeof DashboardSellerOnboardingRoute
  '/dashboard/seller/report': typeof DashboardSellerReportRoute
  '/dashboard/seller/store': typeof DashboardSellerStoreRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/buyer': typeof DashboardBuyerIndexRoute
  '/dashboard/seller': typeof DashboardSellerIndexRoute
  '/dashboard/buyer/orders/$orderId': typeof DashboardBuyerOrdersOrderIdRoute
  '/dashboard/seller/orders/$orderId': typeof DashboardSellerOrdersOrderIdRoute
  '/dashboard/seller/products/create': typeof DashboardSellerProductsCreateRoute
  '/dashboard/buyer/orders': typeof DashboardBuyerOrdersIndexRoute
  '/dashboard/seller/orders': typeof DashboardSellerOrdersIndexRoute
  '/dashboard/seller/products': typeof DashboardSellerProductsIndexRoute
  '/dashboard/seller/products/$productId/edit': typeof DashboardSellerProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/$storeSlug/$productSlug': typeof StoreSlugProductSlugRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteWithChildren
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/seller': typeof DashboardSellerRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/$storeSlug/': typeof StoreSlugIndexRoute
  '/dashboard/admin/discounts': typeof DashboardAdminDiscountsRoute
  '/dashboard/buyer/addresses': typeof DashboardBuyerAddressesRoute
  '/dashboard/buyer/cart': typeof DashboardBuyerCartRoute
  '/dashboard/buyer/checkout': typeof DashboardBuyerCheckoutRoute
  '/dashboard/buyer/report': typeof DashboardBuyerReportRoute
  '/dashboard/buyer/wallet': typeof DashboardBuyerWalletRoute
  '/dashboard/seller/onboarding': typeof DashboardSellerOnboardingRoute
  '/dashboard/seller/report': typeof DashboardSellerReportRoute
  '/dashboard/seller/store': typeof DashboardSellerStoreRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
  '/dashboard/seller/': typeof DashboardSellerIndexRoute
  '/dashboard/buyer/orders/$orderId': typeof DashboardBuyerOrdersOrderIdRoute
  '/dashboard/seller/orders/$orderId': typeof DashboardSellerOrdersOrderIdRoute
  '/dashboard/seller/products/create': typeof DashboardSellerProductsCreateRoute
  '/dashboard/buyer/orders/': typeof DashboardBuyerOrdersIndexRoute
  '/dashboard/seller/orders/': typeof DashboardSellerOrdersIndexRoute
  '/dashboard/seller/products/': typeof DashboardSellerProductsIndexRoute
  '/dashboard/seller/products/$productId/edit': typeof DashboardSellerProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/register'
    | '/select-role'
    | '/$storeSlug/$productSlug'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/driver'
    | '/dashboard/seller'
    | '/products/$productId'
    | '/$storeSlug/'
    | '/dashboard/admin/discounts'
    | '/dashboard/buyer/addresses'
    | '/dashboard/buyer/cart'
    | '/dashboard/buyer/checkout'
    | '/dashboard/buyer/report'
    | '/dashboard/buyer/wallet'
    | '/dashboard/seller/onboarding'
    | '/dashboard/seller/report'
    | '/dashboard/seller/store'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
    | '/dashboard/seller/'
    | '/dashboard/buyer/orders/$orderId'
    | '/dashboard/seller/orders/$orderId'
    | '/dashboard/seller/products/create'
    | '/dashboard/buyer/orders/'
    | '/dashboard/seller/orders/'
    | '/dashboard/seller/products/'
    | '/dashboard/seller/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/register'
    | '/select-role'
    | '/$storeSlug/$productSlug'
    | '/dashboard/driver'
    | '/products/$productId'
    | '/$storeSlug'
    | '/dashboard/admin/discounts'
    | '/dashboard/buyer/addresses'
    | '/dashboard/buyer/cart'
    | '/dashboard/buyer/checkout'
    | '/dashboard/buyer/report'
    | '/dashboard/buyer/wallet'
    | '/dashboard/seller/onboarding'
    | '/dashboard/seller/report'
    | '/dashboard/seller/store'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/dashboard/buyer/orders/$orderId'
    | '/dashboard/seller/orders/$orderId'
    | '/dashboard/seller/products/create'
    | '/dashboard/buyer/orders'
    | '/dashboard/seller/orders'
    | '/dashboard/seller/products'
    | '/dashboard/seller/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/register'
    | '/select-role'
    | '/$storeSlug/$productSlug'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/driver'
    | '/dashboard/seller'
    | '/products/$productId'
    | '/$storeSlug/'
    | '/dashboard/admin/discounts'
    | '/dashboard/buyer/addresses'
    | '/dashboard/buyer/cart'
    | '/dashboard/buyer/checkout'
    | '/dashboard/buyer/report'
    | '/dashboard/buyer/wallet'
    | '/dashboard/seller/onboarding'
    | '/dashboard/seller/report'
    | '/dashboard/seller/store'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
    | '/dashboard/seller/'
    | '/dashboard/buyer/orders/$orderId'
    | '/dashboard/seller/orders/$orderId'
    | '/dashboard/seller/products/create'
    | '/dashboard/buyer/orders/'
    | '/dashboard/seller/orders/'
    | '/dashboard/seller/products/'
    | '/dashboard/seller/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SelectRoleRoute: typeof SelectRoleRoute
  StoreSlugProductSlugRoute: typeof StoreSlugProductSlugRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardBuyerRoute: typeof DashboardBuyerRouteWithChildren
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardSellerRoute: typeof DashboardSellerRouteWithChildren
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  StoreSlugIndexRoute: typeof StoreSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/': {
      id: '/$storeSlug/'
      path: '/$storeSlug'
      fullPath: '/$storeSlug/'
      preLoaderRoute: typeof StoreSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/dashboard/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/$productSlug': {
      id: '/$storeSlug/$productSlug'
      path: '/$storeSlug/$productSlug'
      fullPath: '/$storeSlug/$productSlug'
      preLoaderRoute: typeof StoreSlugProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller/': {
      id: '/dashboard/seller/'
      path: '/'
      fullPath: '/dashboard/seller/'
      preLoaderRoute: typeof DashboardSellerIndexRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/buyer/': {
      id: '/dashboard/buyer/'
      path: '/'
      fullPath: '/dashboard/buyer/'
      preLoaderRoute: typeof DashboardBuyerIndexRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/seller/store': {
      id: '/dashboard/seller/store'
      path: '/store'
      fullPath: '/dashboard/seller/store'
      preLoaderRoute: typeof DashboardSellerStoreRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/seller/report': {
      id: '/dashboard/seller/report'
      path: '/report'
      fullPath: '/dashboard/seller/report'
      preLoaderRoute: typeof DashboardSellerReportRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/seller/onboarding': {
      id: '/dashboard/seller/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/seller/onboarding'
      preLoaderRoute: typeof DashboardSellerOnboardingRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/buyer/wallet': {
      id: '/dashboard/buyer/wallet'
      path: '/wallet'
      fullPath: '/dashboard/buyer/wallet'
      preLoaderRoute: typeof DashboardBuyerWalletRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/buyer/report': {
      id: '/dashboard/buyer/report'
      path: '/report'
      fullPath: '/dashboard/buyer/report'
      preLoaderRoute: typeof DashboardBuyerReportRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/buyer/checkout': {
      id: '/dashboard/buyer/checkout'
      path: '/checkout'
      fullPath: '/dashboard/buyer/checkout'
      preLoaderRoute: typeof DashboardBuyerCheckoutRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/buyer/cart': {
      id: '/dashboard/buyer/cart'
      path: '/cart'
      fullPath: '/dashboard/buyer/cart'
      preLoaderRoute: typeof DashboardBuyerCartRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/buyer/addresses': {
      id: '/dashboard/buyer/addresses'
      path: '/addresses'
      fullPath: '/dashboard/buyer/addresses'
      preLoaderRoute: typeof DashboardBuyerAddressesRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/admin/discounts': {
      id: '/dashboard/admin/discounts'
      path: '/discounts'
      fullPath: '/dashboard/admin/discounts'
      preLoaderRoute: typeof DashboardAdminDiscountsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/seller/products/': {
      id: '/dashboard/seller/products/'
      path: '/products'
      fullPath: '/dashboard/seller/products/'
      preLoaderRoute: typeof DashboardSellerProductsIndexRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/seller/orders/': {
      id: '/dashboard/seller/orders/'
      path: '/orders'
      fullPath: '/dashboard/seller/orders/'
      preLoaderRoute: typeof DashboardSellerOrdersIndexRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/buyer/orders/': {
      id: '/dashboard/buyer/orders/'
      path: '/orders'
      fullPath: '/dashboard/buyer/orders/'
      preLoaderRoute: typeof DashboardBuyerOrdersIndexRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/seller/products/create': {
      id: '/dashboard/seller/products/create'
      path: '/products/create'
      fullPath: '/dashboard/seller/products/create'
      preLoaderRoute: typeof DashboardSellerProductsCreateRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/seller/orders/$orderId': {
      id: '/dashboard/seller/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/seller/orders/$orderId'
      preLoaderRoute: typeof DashboardSellerOrdersOrderIdRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/buyer/orders/$orderId': {
      id: '/dashboard/buyer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/buyer/orders/$orderId'
      preLoaderRoute: typeof DashboardBuyerOrdersOrderIdRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/seller/products/$productId/edit': {
      id: '/dashboard/seller/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/dashboard/seller/products/$productId/edit'
      preLoaderRoute: typeof DashboardSellerProductsProductIdEditRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminDiscountsRoute: typeof DashboardAdminDiscountsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminDiscountsRoute: DashboardAdminDiscountsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardBuyerRouteChildren {
  DashboardBuyerAddressesRoute: typeof DashboardBuyerAddressesRoute
  DashboardBuyerCartRoute: typeof DashboardBuyerCartRoute
  DashboardBuyerCheckoutRoute: typeof DashboardBuyerCheckoutRoute
  DashboardBuyerReportRoute: typeof DashboardBuyerReportRoute
  DashboardBuyerWalletRoute: typeof DashboardBuyerWalletRoute
  DashboardBuyerIndexRoute: typeof DashboardBuyerIndexRoute
  DashboardBuyerOrdersOrderIdRoute: typeof DashboardBuyerOrdersOrderIdRoute
  DashboardBuyerOrdersIndexRoute: typeof DashboardBuyerOrdersIndexRoute
}

const DashboardBuyerRouteChildren: DashboardBuyerRouteChildren = {
  DashboardBuyerAddressesRoute: DashboardBuyerAddressesRoute,
  DashboardBuyerCartRoute: DashboardBuyerCartRoute,
  DashboardBuyerCheckoutRoute: DashboardBuyerCheckoutRoute,
  DashboardBuyerReportRoute: DashboardBuyerReportRoute,
  DashboardBuyerWalletRoute: DashboardBuyerWalletRoute,
  DashboardBuyerIndexRoute: DashboardBuyerIndexRoute,
  DashboardBuyerOrdersOrderIdRoute: DashboardBuyerOrdersOrderIdRoute,
  DashboardBuyerOrdersIndexRoute: DashboardBuyerOrdersIndexRoute,
}

const DashboardBuyerRouteWithChildren = DashboardBuyerRoute._addFileChildren(
  DashboardBuyerRouteChildren,
)

interface DashboardSellerRouteChildren {
  DashboardSellerOnboardingRoute: typeof DashboardSellerOnboardingRoute
  DashboardSellerReportRoute: typeof DashboardSellerReportRoute
  DashboardSellerStoreRoute: typeof DashboardSellerStoreRoute
  DashboardSellerIndexRoute: typeof DashboardSellerIndexRoute
  DashboardSellerOrdersOrderIdRoute: typeof DashboardSellerOrdersOrderIdRoute
  DashboardSellerProductsCreateRoute: typeof DashboardSellerProductsCreateRoute
  DashboardSellerOrdersIndexRoute: typeof DashboardSellerOrdersIndexRoute
  DashboardSellerProductsIndexRoute: typeof DashboardSellerProductsIndexRoute
  DashboardSellerProductsProductIdEditRoute: typeof DashboardSellerProductsProductIdEditRoute
}

const DashboardSellerRouteChildren: DashboardSellerRouteChildren = {
  DashboardSellerOnboardingRoute: DashboardSellerOnboardingRoute,
  DashboardSellerReportRoute: DashboardSellerReportRoute,
  DashboardSellerStoreRoute: DashboardSellerStoreRoute,
  DashboardSellerIndexRoute: DashboardSellerIndexRoute,
  DashboardSellerOrdersOrderIdRoute: DashboardSellerOrdersOrderIdRoute,
  DashboardSellerProductsCreateRoute: DashboardSellerProductsCreateRoute,
  DashboardSellerOrdersIndexRoute: DashboardSellerOrdersIndexRoute,
  DashboardSellerProductsIndexRoute: DashboardSellerProductsIndexRoute,
  DashboardSellerProductsProductIdEditRoute:
    DashboardSellerProductsProductIdEditRoute,
}

const DashboardSellerRouteWithChildren = DashboardSellerRoute._addFileChildren(
  DashboardSellerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SelectRoleRoute: SelectRoleRoute,
  StoreSlugProductSlugRoute: StoreSlugProductSlugRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardBuyerRoute: DashboardBuyerRouteWithChildren,
  DashboardDriverRoute: DashboardDriverRoute,
  DashboardSellerRoute: DashboardSellerRouteWithChildren,
  ProductsProductIdRoute: ProductsProductIdRoute,
  StoreSlugIndexRoute: StoreSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
