/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as DashboardSellerRouteImport } from './routes/dashboard/seller'
import { Route as DashboardDriverRouteImport } from './routes/dashboard/driver'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard/buyer'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as StoreSlugProductSlugRouteImport } from './routes/$storeSlug/$productSlug'

const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/dashboard/seller',
  path: '/dashboard/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugProductSlugRoute = StoreSlugProductSlugRouteImport.update({
  id: '/$storeSlug/$productSlug',
  path: '/$storeSlug/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/$storeSlug/$productSlug': typeof StoreSlugProductSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/$storeSlug/$productSlug': typeof StoreSlugProductSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/$storeSlug/$productSlug': typeof StoreSlugProductSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/register'
    | '/select-role'
    | '/$storeSlug/$productSlug'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/driver'
    | '/dashboard/seller'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/register'
    | '/select-role'
    | '/$storeSlug/$productSlug'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/driver'
    | '/dashboard/seller'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/register'
    | '/select-role'
    | '/$storeSlug/$productSlug'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/driver'
    | '/dashboard/seller'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SelectRoleRoute: typeof SelectRoleRoute
  StoreSlugProductSlugRoute: typeof StoreSlugProductSlugRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardSellerRoute: typeof DashboardSellerRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/dashboard/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/$productSlug': {
      id: '/$storeSlug/$productSlug'
      path: '/$storeSlug/$productSlug'
      fullPath: '/$storeSlug/$productSlug'
      preLoaderRoute: typeof StoreSlugProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SelectRoleRoute: SelectRoleRoute,
  StoreSlugProductSlugRoute: StoreSlugProductSlugRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  DashboardSellerRoute: DashboardSellerRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
